version: "3.8"

services:
    schema:
        image: node:20-slim
        volumes:
            - ./spec:/app/spec
            - ./src:/app/src
            - ./.github/scripts:/app/scripts
        command:
            - /bin/bash
            - -c
            - /app/scripts/openapi.sh
        stop_grace_period: 1s

    server:
        build: .
        working_dir: /app/src
        command: npm start
        tty: true
        depends_on:
            - schema
        volumes:
            - ./src:/app/src
        ports:
            - "8080:8080"
        environment:
            NODE_ENV: dev
            PORT: 8080
        stop_grace_period: 1s

        # ---- OpenAPI Docs server ---- #
    docs:
        image: ahmadnassri/rapidoc-server:1.0.8
        ports:
            - 8000:8080
        volumes:
            - ./spec:/spec
        environment:
            spec-url: /spec/openapi.yml
            render-style: focused
            schema-style: table
            schema-description-expanded: "true"
            show-info: "false"
            show-header: "false"
        stop_grace_period: 1s
