version: "3.8"

services:
    schema:
        image: node:20-slim
        volumes:
            - ./spec:/app/spec
            - ./src:/app/src
            - ./.github/scripts:/app/scripts
        command:
            - /bin/bash
            - -c
            - |
                npm install -g --ignore-scripts --quiet @redocly/cli@latest nodemon
                until redocly --version; do sleep 1; done
                npx nodemon --watch /spec --ext yml --exec sh /app/scripts/openapi.sh
        stop_grace_period: 1s

    server:
        build: .
        working_dir: /app/src
        command: npm start
        tty: true
        depends_on:
            - schema
        volumes:
            - ./src:/app/src
        ports:
            - "8080:8080"
        environment:
            NODE_ENV: dev
            PORT: 8080
        stop_grace_period: 1s
